### ISSUE TITLE
Problemas con la github actions de coveralls, no se ejecuta.

### ISSUE THREAD

**Issue by JoelFEscobar** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-m#4]
Buenas noches @esegredo .
Tenemos un problema con la Github actions de Coveralls he seguido al pie de la letra el video que se encuentra en el aula virtual de la asignatura y al pushear los cambios de mi maquina a Github y ejecutar la action referente a coveralls, esta no se ejecuta. He mirado posibles fallos de sintaxis y he hecho el repositorio Publico por si es debido a la visibilidad del mismo, pero sigue sin funcionar. Adjunto el codigo correspondiente a la action:

```YML
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Installing dependencies
      run: npm install
    - name: Generating coverage information
      run: npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

```
un saludo y gracias de antemano.
